MX1356 + MX1364 add data drop api for x-systems
robert-koch-institut/mex-drop pull request #1
Opened 2023-07-14 08:13 UTC by rababerladuseladim

- spin up: `poetry run drop`
- visit: http://localhost:8081/docs
- also addresses MX-1364

2023-07-14 10:00 UTC, cutoffthetop commented on tests/test_main.py
> +class AsyncMock(MagicMock):
`unittest.mock.AsyncMock` not good?

2023-07-14 10:02 UTC, cutoffthetop commented on mex/drop/settings.py
> +        8080,
i would vote for a different default port, to reduce the hassle of starting multiple backend services simultaniously (with default config)

2023-07-14 11:41 UTC, rababerladuseladim commented on mex/__init__.py
> +__path__ = extend_path(__path__, __name__)
added in 17ec03667f35af6112a706224fe2dabdeb092170

2023-07-14 11:47 UTC, rababerladuseladim commented on mex/drop/main.py
> +    prefix="/api/v0",
adapted in ceff4ecd0e276bcaa426f5eb7d621e58206b29a9

2023-07-14 11:49 UTC, rababerladuseladim commented on Makefile
> +docs:
Indeed, nice find. I removed the section in e260f204971d534fb2bbdd6168774d4b976fb280

2023-07-14 11:51 UTC, rababerladuseladim commented on mex/drop/main.py
> +@router.post("/{x_system}/{entity_type}", status_code=201)
changed in e2efbeeaef233983acfd7be5f40df261d437c721

2023-07-14 11:55 UTC, rababerladuseladim commented on mex/drop/main.py
> +            headers={"X-API-Key": ""},
I adapted it from the [fastapi tutorial](https://fastapi.tiangolo.com/tutorial/security/simple-oauth2/#code-to-get-the-username-and-password), which respond with this (almost) empty header: `{"WWW-Authenticate": "Bearer"}`. I have no strong feelings regarding this, though. Shall I drop it?

2023-07-14 11:59 UTC, rababerladuseladim commented on mex/drop/security.py
> +    if not x_systems:
I liked the idea of separate error messages for failed authorization and a lack of authorization for the current x-system. I am open to merging these into one, though. What do you prefer?

2023-07-14 12:03 UTC, rababerladuseladim commented on mex/drop/settings.py
> +    drop_root_path: str = Field(
adapted in 2da147f45a886d41259c602241a177ec761b6c67

2023-07-14 12:08 UTC, rababerladuseladim commented on mex/drop/sinks/json.py
> +async def json_sink(data: dict[str, Any], out_file: Path) -> None:
I lack understanding for async, I followed my gut. Removed async in 99e928e7fda5997a4ca7593e9698b7a2678e8cdc

2023-07-14 12:11 UTC, rababerladuseladim commented on mex/drop/types/user_database.py
> +UserDatabase = dict[str, list[str]]
I fiddled around with `SecretStr` but couldn't come up with a neat solution... Thank you, adapted in 0cae9f8f6d85e621c858d6e04c579d5b36ce4261

2023-07-14 12:12 UTC, rababerladuseladim commented on mex/drop/settings.py
> +        "data",
added in 7655a3799738d5047408fa5ff6fe67d0ac934cd8

2023-07-14 12:14 UTC, rababerladuseladim commented on mex/drop/main.py
> +    await json_sink(data, out_file)
Does this still apply if `json_sink` is not async anymore?

2023-07-14 12:29 UTC, rababerladuseladim commented on mex/drop/security.py
> +    Raises HTTPException if user is not present
adapted in 8a2c5d547ad7d7dab44c094988d6d846f4db6afd

2023-07-14 12:30 UTC, rababerladuseladim commented on mex/drop/types/user_database.py
> +UserDatabase = dict[str, list[str]]
Aaaand reverted in 7b93d57fa84698e0b5eb2ecf19c412221a17f5ce. Unfortunately, the keys are the really sensitive part. And dictionary lookup fails if I turn them into `SecretStr`. :-( Any other ideas?

2023-07-14 12:32 UTC, rababerladuseladim commented on mex/drop/main.py
> +        None
adapted in 9068a2444219b2739f05cc3b1343e0db0d41abc5

2023-07-14 12:32 UTC, rababerladuseladim commented on tests/test_main.py
> +class AsyncMock(MagicMock):
deleted, since json sync is not async anymore.

2023-07-14 12:34 UTC, rababerladuseladim commented on mex/drop/settings.py
> +        8080,
good point. Changed to 8081 in 877625d50dd12eb8325100a5e152644a6498002d

2023-07-14 12:35 UTC, rababerladuseladim commented
@cutoffthetop back to you.

2023-07-17 09:25 UTC, cutoffthetop commented on mex/drop/sinks/json.py
> +async def json_sink(data: dict[str, Any], out_file: Path) -> None:
async really only makes sense when you have non-blocking io. `with open(): json.dump()` has blocking disk io though

2023-07-17 09:29 UTC, cutoffthetop commented on mex/drop/types/user_database.py
> +UserDatabase = dict[str, list[str]]
ah right, the lookup direction is currently `token -> list of allowed-x-systems`. could you turn it around into `x-system -> allowed tokens`?

2023-07-17 09:35 UTC, cutoffthetop commented on mex/drop/main.py
> +    await json_sink(data, out_file)
yes that works. i think under-the-hood, it's the same as https://fastapi.tiangolo.com/tutorial/background-tasks/?h=background#create-a-task-function

> It can be an async def or normal def function, FastAPI will know how to handle it correctly.

2023-07-17 09:40 UTC, cutoffthetop commented on mex/drop/security.py
> +    if not x_systems:
ah, gotcha. leave this in then

2023-07-17 09:45 UTC, cutoffthetop requested changes

2023-07-17 09:45 UTC, cutoffthetop commented on mex/drop/main.py
> +            status_code=status.HTTP_401_UNAUTHORIZED,
this should be a [403](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403) as in "we know who you are, but you are not allowed to be here". wheras [this](https://github.com/robert-koch-institut/mex-drop/pull/1/files#r1263653054) can remain a [401](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401) "we don't even know you, go away"

2023-07-18 15:02 UTC, cutoffthetop commented on mex/drop/main.py
> +            status_code=status.HTTP_401_UNAUTHORIZED,
fixed in 677ee2c

2023-07-18 15:04 UTC, cutoffthetop commented on mex/drop/main.py
> +            headers={"X-API-Key": ""},
removed in 677ee2c

2023-07-18 15:05 UTC, cutoffthetop commented on mex/drop/types/user_database.py
> +UserDatabase = dict[str, list[str]]
turning it around was not necessary, just needed to wrap the key in SecretStr too (677ee2c)

2023-07-18 15:06 UTC, cutoffthetop approved these changes

2023-07-20 12:35 UTC, rababerladuseladim commented on mex/drop/settings.py
> +                key
Shouldn't this be `key: x_systems`?

2023-07-20 12:43 UTC, cutoffthetop commented on mex/drop/settings.py
> +                key
except for the type enforcements, that's exactly what it says 🤷

2023-07-21 10:51 UTC, mr-kamran-ali approved these changes
Neat and clean. Awesome job. <3

2023-07-21 10:52 UTC, mr-kamran-ali approved these changes

2023-07-21 13:52 UTC, cutoffthetop approved these changes

2023-07-21 13:55 UTC, merged