first commit
robert-koch-institut/mex-drop pull request #120
Opened 2024-07-18 13:47 UTC by ZehraVictoria

# PR Context

# Added

# Changes

# Deprecated

# Removed

# Fixed

# Security

2024-07-26 13:08 UTC, cutoffthetop requested changes
nice! congrats on your first PR 🎉🎇

very clean overall, i have just a few small suggestions

2024-07-26 13:08 UTC, cutoffthetop commented on mex/drop/main.py
> +        out_file.parent.mkdir(parents=True, exist_ok=True)
i'd probably defer this to the `write_to_file` function as well. that way all disk i/o happens in a background task

2024-07-26 13:08 UTC, cutoffthetop commented on mex/drop/main.py
> +        raise HTTPException(
not sure this will work, the request already returned a 202 status code and this function is only called by fastapi *after* that.

you could just replace the `HTTPException` with `mex.common.exceptions.MExError` and remove the status code

2024-07-26 13:08 UTC, cutoffthetop commented on tests/test_main.py
> +        ("api-test-key", "test_system", 202, {"file1.txt": "file1 content"}),
```suggestion
        ("api-test-key", "test_system", 202, {"file1.txt": "file1 content", "file2.csv": "1,2,3"}),
```

let's try with a second file as well, to justify the test name `test_drop_multiple_files` 🙃

2024-07-26 13:08 UTC, cutoffthetop commented on mex/drop/main.py
> +        list[UploadFile],  # or list[dict[str, Any]] | list[list[Any]],
mh? 😄

2024-07-29 10:30 UTC, cutoffthetop commented on mex/drop/main.py
> +        out_file.parent.mkdir(parents=True, exist_ok=True)
but instead of on `out_file.parent` you could just call `mkdir` directly on the `drop_directory`, right?

`Path(settings.drop_directory).mkdir(parents=True, exist_ok=True)`

2024-08-01 08:44 UTC, ZehraVictoria commented on mex/drop/main.py
> +        out_file.parent.mkdir(parents=True, exist_ok=True)
`Path(settings.drop_directory).mkdir(parents=True, exist_ok=True)` didnt work unfortunetly, but `using out_file.parent ` in the backgroundtask should work as well?

2024-08-05 08:48 UTC, cutoffthetop commented on mex/drop/main.py
> +        out_file.parent.mkdir(parents=True, exist_ok=True)
yep, that works too

2024-08-05 08:50 UTC, cutoffthetop approved these changes
ready to merge 🚀

2024-08-05 09:41 UTC, merged