mx-1632 structured file support
robert-koch-institut/mex-drop pull request #134
Opened 2024-08-01 11:29 UTC by ZehraVictoria

# PR Context

# Added

# Changes

# Deprecated

# Removed

# Fixed

# Security

2024-08-21 10:55 UTC, mr-kamran-ali reviewed
Nice work. Few little things to fix.

2024-08-21 10:55 UTC, mr-kamran-ali commented on requirements.txt
> +reflex==0.5.8
We have reflex in `pyproject.toml` this is being added here by some hook, which is also modifying `gitignore`. its better to remove `reflex` from here.

2024-08-21 10:55 UTC, mr-kamran-ali commented on .gitignore
our `gitignore` structure was better. this is being modified by some hook. Can you please restore it?

2024-08-21 10:55 UTC, mr-kamran-ali commented on mex/drop/api.py
> +            file_stream = io.BytesIO(content)
this `elif` block is not being tested. thats why total coverage is not reaching 95%. can you verify its being tested in calling endpoints?

2024-08-23 11:47 UTC, mr-kamran-ali commented on tests/test_main.py
> +@pytest.mark.skip(reason="features not implemented yet")
this is what causing the screen shot upload action to fail. this test is skipped so no screen shots are created. Can you remove this line and see if all actions pass?

2024-08-27 09:25 UTC, ZehraVictoria commented on tests/test_main.py
> +@pytest.mark.skip(reason="features not implemented yet")
Thanks, that absolutely fixed it!

2024-08-29 10:32 UTC, rababerladuseladim requested changes
Nice work! I do have a few remarks.

First and foremost: One test fails locally: `tests/test_main.py::test_index[firefox]`

2024-09-03 10:23 UTC, ZehraVictoria commented on tests/test_api.py
> +        for name, (content, content_type) in files.items()
That would make `files_data` incompatible with the` files` parameter from `client.post` (Exact error: Argument of type "list[tuple[str, BytesIO, str]]" cannot be assigned to parameter "files" of type "RequestFiles | None" in function "post")

2024-09-06 07:03 UTC, rababerladuseladim commented on pyproject.toml
> +    "reflex>=0.5.9,<1",
mex-common and reflex are still duplicates, please remove. And what is playright used for? Isn't it only a testing dependency? If yes: please move to dev-dependencies.

2024-09-06 07:31 UTC, rababerladuseladim commented on mex/drop/api.py
> +            detail=f"Unsupported file extension: {type}",
This is also a bad request, isn't it? And the error could contain the allowed content types, to make the life of the users easier.

But after a doing some research, I found an even better error code: [422 Unprocessable Content](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422)

2024-09-06 08:00 UTC, rababerladuseladim commented
And one more: could you document the allowed file types in swagger as well? That makes using the API easier.

2024-09-10 14:18 UTC, ZehraVictoria commented on mex/drop/api.py
> +        hash_bucket.add(file.filename)
Used in 5c69fc5

2024-09-10 14:18 UTC, ZehraVictoria commented on mex/drop/api.py
> +        return Response(status_code=200)
Fixed in 5c69fc5

2024-09-10 14:18 UTC, ZehraVictoria commented on mex/drop/api.py
> +        data: data content of request body (dict, list or bytes)
Fixed in 5c69fc5

2024-09-10 14:18 UTC, ZehraVictoria commented on mex/drop/api.py
>                  "<root><foo>bar</foo></root>",
Fixed in 5c69fc5

2024-09-10 15:05 UTC, ZehraVictoria commented on pyproject.toml
> +    "reflex>=0.5.9,<1",
rm duplicates and playright in d74f846b5af0128f26637f63dea8c13ab09ab922

2024-09-10 17:27 UTC, ZehraVictoria commented on tests/test_api.py
> +        for name, (content, content_type) in files.items()
fixed in 5c69fc5e73f0eeb983ff7935cbb09d0e9b6bf1e8

2024-09-10 17:27 UTC, ZehraVictoria commented on tests/test_api.py
> +        ).with_suffix(ALLOWED_CONTENT_TYPES[content_type])
fixed in 5c69fc5e73f0eeb983ff7935cbb09d0e9b6bf1e8

2024-09-10 17:36 UTC, ZehraVictoria commented on mex/drop/api.py
> +            detail=f"Unsupported file extension: {type}",
fixed in 96353b6bae23b9886e76323a53f1b33d07f0aa41

2024-09-10 17:52 UTC, ZehraVictoria commented on pyproject.toml
> +    "pandas-stubs>=2.2.2.240807,<3",
I actually removed the pandas-stubs, instead of openpyxl since that is still needed for testing in the current code.

2024-09-11 13:02 UTC, rababerladuseladim commented on pyproject.toml
> +    "pandas-stubs>=2.2.2.240807,<3",
well, true, But since we do not parse it, a bytes comparison without pandas would be sufficient for me. Let's fix this when bored, though.

2024-09-12 10:26 UTC, rababerladuseladim requested changes
Biu-ti-ful! And almost there, just some tiny nitpicking left.

2024-09-12 10:26 UTC, rababerladuseladim commented on mex/drop/api.py
> +    return Response(status_code=200)
Just a question: why do you not add the background task to the Response anymore?

2024-09-12 10:26 UTC, rababerladuseladim commented on mex/drop/api.py
> +    check_duplicate_filenames(files)
Could you add a test case with duplicate filenames?

2024-09-12 10:26 UTC, rababerladuseladim commented on mex/drop/files_io.py
> +            status_code=status.HTTP_400_BAD_REQUEST,
This should also be a 422, shouldn't it? Same for line 67.

2024-09-12 13:14 UTC, ZehraVictoria commented on mex/drop/api.py
> +    return Response(status_code=200)
no reason really. Happy to change it back :)

2024-09-13 08:02 UTC, rababerladuseladim requested changes
oh boi, just one tiny thing left.

2024-09-13 08:02 UTC, rababerladuseladim commented on mex/drop/api.py
> +from starlette.background import BackgroundTask, BackgroundTasks
Now you do not need the `BackgroundTasks` anmore, do you?

2024-09-26 08:54 UTC, ZehraVictoria commented on mex/drop/api.py
> +from starlette.background import BackgroundTask, BackgroundTasks
`BackgroundTasks` is still used in multipart upload. but I removed it from the single file drop function: 86eec1301f7640b7e5209c1d755733ef59df1431

2024-09-26 14:07 UTC, merged