initial push
robert-koch-institut/mex-drop pull request #163
Opened 2024-08-22 08:42 UTC by ZehraVictoria

# Added
creates reflex mini-UI in mex-drop for library team to send endnote XMLs

2024-10-16 14:10 UTC, cutoffthetop requested changes
very nice and clean! i tried it out locally, and it's working smoothly.
i have just some smaller suggestions and ideas, and a request for some integration tests

2024-10-16 14:10 UTC, cutoffthetop commented on tests/test_main.py
> +        assert len(app_state.temp_files) == 0
these are actually solid unit tests 👍 but, they are not testing code in `main.py`, so i'd move them to `tests/test_state.py`

and then, could you add a couple of integration tests as well? where we actually upload a file and check it being written to disk. should be quite doable using playwright -> https://playwright.dev/docs/input#upload-files

the test `test_index` already uses playwright for an integration test, but you can also take a peak over to the editor, eg here https://github.com/robert-koch-institut/mex-editor/blob/0.5.0/tests/search/test_main.py

2024-10-17 12:30 UTC, ZehraVictoria commented on mex/drop/main.py
> +                    rx.card(
fixed in 1d4001c5942613367f6f9f5484aa6cc5a79da2b6

2024-10-22 11:53 UTC, ZehraVictoria commented on mex/drop/main.py
> +                                    rx.upload_files(upload_id="upload_one")
fixed in fce9a529f43c4290cb7980ce3d413dd2085d401c

2024-10-22 11:54 UTC, ZehraVictoria commented on mex/drop/state.py
> +        return cls._instance
superfluous helper function deleted in fce9a529f43c4290cb7980ce3d413dd2085d401c

2024-11-06 08:27 UTC, cutoffthetop approved these changes
looks good! ready to merge 💯

2024-11-06 08:27 UTC, merged