Feature/mx 1380 update pydantic to v2
robert-koch-institut/mex-drop pull request #22
Opened 2023-10-13 14:24 UTC by rababerladuseladim

- update pydantic to v2

2023-11-16 15:29 UTC, cutoffthetop requested changes
nice! only needs the post-pydantic-2 mex-common version, and then it's good to merge

2023-11-16 15:29 UTC, cutoffthetop commented on mex/drop/settings.py
> +    @field_validator("drop_user_database", mode="before")
this option name is still quite confusing 🙈

2023-11-17 12:39 UTC, rababerladuseladim commented on mex/drop/settings.py
> +    @field_validator("drop_user_database", mode="before")
chatgpt did not help:
> drop_store_user_database
> drop_save_user_data
> drop_archive_user_db
> drop_backup_user_database
> drop_preserve_user_data
> drop_export_user_db
> drop_record_user_database
> drop_store_user_records
> drop_backup_user_data
> drop_capture_user_db

2023-11-17 13:10 UTC, cutoffthetop approved these changes

2023-11-17 13:18 UTC, merged