Feature/mx 1538 add download endpoint
robert-koch-institut/mex-drop pull request #46
Opened 2024-01-31 10:54 UTC by rababerladuseladim

# PR Context

Instead of adding a dedicated `read` permission, I opted for a dummy `admin` x-system, which has read/write access to all endpoints.

## Added
- endpoint for listing available x-systems (requires authentication for x-system `admin`)
- endpoint for listing downloadable files for an x-system
- endpoint for downloading data

## Changed
- Update dependencies
- **BREAKING** rename setting `MEX_DROP_USER_DATABASE` to `MEX_DROP_API_KEY_DATABASE`

## Removed
- **BREAKING** remove the upload html form at `/v0/{x_system}/{entity_type}`, because the endpoint conflicted with the most obvious route for downloading files (GET /v0/x-system/entity)

2024-03-11 18:05 UTC, cutoffthetop requested changes
pretty, clean.

just smaller stuff and a missing main-merge

2024-03-12 13:21 UTC, rababerladuseladim commented on mex/drop/main.py
> +        return Response(content=handle.read(), status_code=202)
because of copy&paste f***-up...
fixed in 9546f41660c59a4d854aa4e53d00e0fc70119a96

2024-03-12 13:33 UTC, rababerladuseladim commented on mex/drop/main.py
> +        for f in settings.drop_directory._path.glob("*")
another way found in 2afde11064ef1b67c1dac6faa5700786c90914b8

2024-03-12 13:40 UTC, rababerladuseladim commented on mex/drop/main.py
> +) -> list[str]:
adapted in 4c81be9e8f05b9322f676db3f8d3b7532dfb30e5

2024-03-12 13:40 UTC, rababerladuseladim commented on mex/drop/main.py
> +) -> list[str]:
adapted in 4c81be9e8f05b9322f676db3f8d3b7532dfb30e5

2024-03-12 13:41 UTC, rababerladuseladim commented on mex/drop/main.py
> +def list_files(
done in af8e4c4c75c28d6329ab0078580ebd48643a0246

2024-03-12 13:42 UTC, rababerladuseladim commented
main is merged, could you have another look?

2024-03-12 13:52 UTC, cutoffthetop approved these changes

2024-03-12 13:53 UTC, merged